name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_news
          postgresql user: nenad
          postgresql password: password

      - name: install dependencies
        run: npm i

      - name: test entire app
        run: PGDATABASE=nc_news PGUSER=nenad PGPASSWORD=password npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
